---
title: "Boris Polanco"

---
============

-------------------     ----------------------------
Gerliswilstrasse 10                boris.polanco@paraplegie.ch
Lucerne                        @twitter_handle
Switzerland                           1800 my-phone-nr
-------------------     ----------------------------

Education
---------

2021-Currently
:   **PhD, Health Sciences**; University of Lucerne 

2016-2018
:   **Msc, Statistics**; University of Bern 

    
2007-2015
:   **BSc, Mathmatical Engineering**; Escuela Politécnica Nacional
    Quito-Ecuador

    *Thesis: Late Life Mortality Decelation in Ecuadorian Population*

Experience
----------

**Actuary at the Ecuadorian Institute of Social Security (IESS)**

Short text containing the type of work done, results obtained,
lessons learned and other remarks. Can also include lists and
links:

* First item

* Item with [link](http://www.example.com). Links will work both in
  the html and pdf versions.

**Actuarial Consultant (Actuaria Consultores)**

Also with a short description.

**Survey Design Analyst at the National Institute of Statistics and Census Bureau (INEC)**

Technical Experience
--------------------

My Cool Side Project
:   For items which don't have a clear time ordering, a definition
    list can be used to have named items.

    * These items can also contain lists, but you need to mind the
      indentation levels in the markdown source.
    * Second item.

Open Source
:   List open source contributions here, perhaps placing emphasis on
    the project names, for example the **Linux Kernel**, where you
    implemented multithreading over a long weekend, or **node.js**
    (with [link](http://nodejs.org)) which was actually totally
    your idea...