---
title: "Various about statistics and insurance"

---



## The Compound Process
Is a random sum where the upper summation index is a counting process.
In general we have that:
$$Z_t=\sum_{j=0}^{N_t}X_j$$
It is called the total loss or the total claim amount.
Is easy to prove that the moment generating function of $Z_t$ is given by $$M_{Z_t}(v)=M_{N_t}(log(M_X(v)))$$
In addition to that, we know the next property of the moment generating function:
$$E(X^k)=M^{(k)}(0)$$
Using this fact, we can get the expected value for the total loss or total calim amount.
\begin{align*}
E(Z_t)&=M'_{N_t}(log(M_X(0)))\times\frac{M'_X(0)}{M_X(0)}\\
E(Z_t)&=E(N_t)E(X_1)
\end{align*}


## The Risk Process

We consider $X_1,X_2,...$ independent individual random losses or claim amounts, with distribution function $F$ 

$k_t$: Individual number of claims ocurring during $[0,t]$ $\forall t\geq 0$. 

$\{k_t\}_{t\geq 0}$: Is a birth process independent of $\{X_k\}_{k\geq 1}$

The $\textbf{total loss}$ or $\textbf{claim amount}$ is  $$Z_t=\sum_{k=0}^{k_t}X_k$$ where $X_0=0$.

Let $r_0$ the initial capital and $c>0$ be the premium rate (assumed constant)

$$Y_t=r_o+ct-Z_t$$ is the risk process.

## Heavy and Light tails in  Non life Insurance.

In general insurance, is introduced the concept of heavy and light tailed distributions.  The basic interpretation of it is:

- A distribution is light tailed, if is assigned smaller probabilities for larger  values of the variable $x$.

- A distribution is heavy tailed, if is assigned larger probabilities to larger values of the variable $x$.

$\textbf{Some examples:}$  For heavy tailed distributions we have for instance: 

-The top of the $1\%$ of the world has the $40\%$ of the wealth.

-The top of the $2\%$ of twitter users post the $60\%$ of tweets

